# Generated by Django 4.2.6 on 2023-11-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bith_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Okrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Uchastok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.CharField(max_length=200)),
                ('okrug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tele.okrug')),
            ],
        ),
        migrations.CreateModel(
            name='list_Uchastkov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
                ('uchastok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tele.uchastok')),
            ],
        ),
        migrations.CreateModel(
            name='kartochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tele.list_uchastkov')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tele.bith_year')),
            ],
        ),
        migrations.AddField(
            model_name='bith_year',
            name='uchastok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tele.uchastok'),
        ),
    ]
