# Generated by Django 4.2.7 on 2023-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0003_alter_article_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
