# Generated by Django 4.2.7 on 2023-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0004_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
