# Generated by Django 4.2.7 on 2023-11-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0005_alter_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/img', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='kartochka',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='kartochka',
            name='year',
        ),
        migrations.RemoveField(
            model_name='list_uchastkov',
            name='uchastok',
        ),
        migrations.RemoveField(
            model_name='uchastok',
            name='okrug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='msg',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.DeleteModel(
            name='bith_year',
        ),
        migrations.DeleteModel(
            name='kartochka',
        ),
        migrations.DeleteModel(
            name='list_Uchastkov',
        ),
        migrations.DeleteModel(
            name='Okrug',
        ),
        migrations.DeleteModel(
            name='Uchastok',
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tele.article'),
        ),
    ]
